version: '3.4'

services:
  shakespearepokemons:
    image: ${DOCKER_REGISTRY-}shakespearepokemons
    build:
      context: .
      dockerfile: ShakespearePokemons/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"