name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        source-url: https://nuget.pkg.github.com/facundo91/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}
    - name: Change Folder
      run: cd .\ShakespearePokemons.Client\
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Package
      run: dotnet pack -c Release
    - name: Publish
      run: dotnet nuget push ShakespearePokemons.Client/bin/Release/*.nupkg --skip-duplicate
