name: Publish Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        source-url: https://nuget.pkg.github.com/facundo91/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore
      working-directory: ShakespearePokemons.Client
    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: ShakespearePokemons.Client
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ShakespearePokemons.Client
    - name: Package
      run: dotnet pack -c Release
      working-directory: ShakespearePokemons.Client
    - name: Publish
      run: dotnet nuget push bin/Release/*.nupkg --skip-duplicate
      working-directory: ShakespearePokemons.Client
